title: ESPHome-Configs.io
description: >- # this means to ignore newlines until "baseurl:"
  A database of configuration files and guides for devices commonly flashed with https://esphome.io firmware.
url: "https://esphome-configs.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - docker-compose.yml
  - README.md
  - CODE-OF-CONDUCT.md

collections:
  devices:
    output: true
    permalink: /devices/:name/
  device-types:
    output: true
    permalink: /types/:name/
  device-standards:
    output: true
    permalink: /standards/:name/
  shared-guides:
    output: true
    permalink: /guides/:name/

defaults:
  -
    scope:
      path: "_devices"
    values:
      layout: "device"
  -
    scope:
      path: "_device-types"
    values:
      layout: "device-types-index"
  -
    scope:
      path: "_device-standards"
    values:
      layout: "device-standards-index"
  -
    scope:
      path: "_shared-guides"
    values:
      layout: "shared-guides-index"

# Theme Settings

# Logo
logo: "/assets/images/esphome-logo.svg"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/


# Heading Anchor Links
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "ESPHome-Configs.io on GitHub":
    - "//github.com/jonathanadams/esphome-configs"
